apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-server
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 2m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/mcp-server
  wait: true
